import tkinter as tk
def btn_clicked():
    my_str.set("ผลการคำนวณคือ...")
    my_height.focus_set()
def my_weight_enter(x):
    btn.focus_set()
def my_height_enter(x):
    my_weight.focus_set()
app = tk.Tk()
app.title("BMI")
app.geometry("320x240")
my_str = tk.StringVar(app)
my_str.set("???")
label1=tk.Label(text="ส่วนสูง(ซม.):",font=("Tahoma",10),width=15,height=2)
label2=tk.Label(text="น้ำหนัก(กก.):",font=("Tahoma",10),width=15,height=2)
label3=tk.Label(textvariable=my_str,font=("Tahoma",12),width=30,height=2)
btn=tk.Button(text="คำนวณ",font=('Tahoma',10,'bold'), command=btn_clicked,width=20, height=3)
my_weight = tk.Entry(font=("Tahoma",10),width=15)
my_height = tk.Entry(font=("Tahoma",10),width=15)
my_weight.bind('<Return>', my_weight_enter)
my_height.bind('<Return>', my_height_enter)
label1.pack()
my_height.pack()
label2.pack()
my_weight.pack()
btn.pack()
label3.pack()
my_height.focus_set()
app.mainloop()
